import { test, expect } from '@playwright/test';
import { users, posts, categories } from '../js/fixtures.js';

// What the export menus offer when the dashboard cannot actually deliver.
//
// Markdown, DBML, JSON and CSV are generated server-side, so a dashboard served
// without an export route cannot produce them. It offered all of them anyway,
// and choosing one threw a TypeError inside a promise: no file, no error, no
// sign anything had happened. That is what the live demo does today.
//
// PNG has the same shape of failure for a different reason. It rasterises
// through a canvas, and past roughly 268 megapixels Chrome hands back a blank
// canvas whose toBlob yields null, which the caller discarded.

const base = {
  connection: 'primary',
  fallback: false,
  skipped_migrations: [],
  generated_at: '2026-07-23T00:00:00Z',
  tables: [users, posts, categories],
  diff: null,
};

/**
 * @param {import('@playwright/test').Page} page
 * @param {{ server?: boolean }} options
 */
async function load(page, { server = true } = {}) {
  await page.route('**/api/schema**', (route) =>
    route.fulfill({ contentType: 'application/json', body: JSON.stringify(base) }));

  if (!server) {
    // Served without the attribute at all, which is what a static page does.
    // It cannot be stripped from a script: truss.js reads its config once, at
    // module evaluation, and a deferred module runs before DOMContentLoaded.
    await page.route('**/harness.html', async (route) => {
      const response = await route.fetch();
      const html = (await response.text()).replace(/\s*data-export-endpoint="[^"]*"/, '');
      await route.fulfill({ response, body: html, contentType: 'text/html' });
    });
  }

  await page.goto('/tests/e2e/harness.html');
  await expect(page.locator('#truss-canvas > svg')).toBeVisible();
}

const openExportMenu = (page) => page.locator('#truss-export-btn').click();

test('offers every export when the route is there', async ({ page }) => {
  await load(page);
  await openExportMenu(page);

  for (const act of ['png', 'svg', 'md', 'dbml']) {
    await expect(page.locator(`#truss-popover button[data-act="${act}"]`))
      .not.toHaveAttribute('aria-disabled', 'true');
  }
  await expect(page.locator('#truss-popover .truss-menu-note')).toHaveCount(0);
});

test('marks the server-backed exports unavailable when there is no route', async ({ page }) => {
  await load(page, { server: false });
  await openExportMenu(page);

  await expect(page.locator('#truss-popover button[data-act="md"]')).toHaveAttribute('aria-disabled', 'true');
  await expect(page.locator('#truss-popover button[data-act="dbml"]')).toHaveAttribute('aria-disabled', 'true');
  // The two that need nothing from a server stay usable.
  await expect(page.locator('#truss-popover button[data-act="png"]')).not.toHaveAttribute('aria-disabled', 'true');
  await expect(page.locator('#truss-popover button[data-act="svg"]')).not.toHaveAttribute('aria-disabled', 'true');
});

test('says why, rather than dimming an item and leaving it at that', async ({ page }) => {
  await load(page, { server: false });
  await openExportMenu(page);

  await expect(page.locator('#truss-popover .truss-menu-note'))
    .toContainText('generated by Truss inside your application');
});

test('keeps an unavailable item reachable by keyboard so its reason can be read', async ({ page }) => {
  // aria-disabled rather than the disabled attribute: a disabled button leaves
  // the tab order, so the item and its explanation vanish for exactly the people
  // who cannot see it dimmed.
  await load(page, { server: false });
  await openExportMenu(page);

  const item = page.locator('#truss-popover button[data-act="dbml"]');
  await item.focus();
  await expect(item).toBeFocused();
});

test('an unavailable item does nothing when it is activated', async ({ page }) => {
  await load(page, { server: false });

  const failures = [];
  page.on('pageerror', (error) => failures.push(String(error)));
  page.on('download', () => failures.push('a download started'));

  await openExportMenu(page);
  // force: true because Playwright honours aria-disabled and would otherwise
  // wait for the item to become enabled, which is worth knowing on its own. The
  // point here is the handler ignoring it even when the click does land.
  await page.locator('#truss-popover button[data-act="dbml"]').click({ force: true });
  await page.locator('#truss-popover button[data-act="md"]').press('Enter');
  await page.waitForTimeout(300);

  expect(failures).toEqual([]);
});

test('the table menu marks its server-backed actions too', async ({ page }) => {
  await load(page, { server: false });

  await page.locator('#truss-canvas [role="button"]').first().click();
  await expect(page.locator('#truss-popover')).toBeVisible();

  for (const act of ['copy', 'json', 'csv', 'table-md']) {
    await expect(page.locator(`#truss-popover button[data-act="${act}"]`))
      .toHaveAttribute('aria-disabled', 'true');
  }
  // Focus needs nothing from a server and must survive.
  await expect(page.locator('#truss-popover button[data-act="focus"]'))
    .not.toHaveAttribute('aria-disabled', 'true');
});
